### PR TITLE
Fixup pin libx11 by bumping the build number

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
I think the defaults changed in conda. or for some reason, now the pinning is always >=1.7 instead of exactly 1.6

**Comment by hmaarrfk** [comment]
Ok this is because the pinnings were changed in https://github.com/conda-forge/xorg-libxcomposite-feedstock/pull/2 but the number wasn't updated.

**Comment by hmaarrfk** [comment]
I don't mean anything malicious by the comment. It is really hard to know when to change and when not to chane the build number.

I was just trying to understand "what changed". 

Thank you for helping maintain and improve these recipes.

**Comment by zklaus** [comment]
No worries. Thank you! Does this close #4?

**Pull request merged**
